[package]
name = "pinentry-anyrun"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
async-std = {version = "1.12.0", features = ["attributes"]}
async-process = "2.2.3"
ron = "0.8"
serde = { version = "1", features = ["derive"] }
